"use server";
import {revalidatePath} from "next/cache";import {redirect} from "next/navigation";import {z} from "zod";import {createClient} from "@/lib/supabase/server";
export type FormState={error?:string};
const schema=z.object({name:z.string().trim().min(1).max(120),species:z.enum(["dog","cat","horse","cattle","buffalo","goat","sheep","other_livestock"]),breed:z.string().trim().max(120).optional(),date_of_birth:z.string().optional(),weight:z.coerce.number().positive().optional().or(z.literal("")),sex:z.string().max(40).optional(),notes:z.string().max(3000).optional()});
export async function createAnimal(_:FormState,data:FormData):Promise<FormState>{const parsed=schema.safeParse(Object.fromEntries(data));if(!parsed.success)return{error:"Check required fields and enter a positive weight."};const supabase=await createClient();const {data:auth}=await supabase.auth.getClaims();const owner_id=auth?.claims?.sub;if(!owner_id)return{error:"Your session expired. Sign in again."};const v=parsed.data;const {data:animal,error}=await supabase.from("animals").insert({owner_id,name:v.name,species:v.species,breed:v.breed||null,date_of_birth:v.date_of_birth||null,weight:v.weight||null,weight_unit:"kg",sex:v.sex||null,notes:v.notes||null}).select("id").single();if(error)return{error:error.message};revalidatePath("/animals");redirect(`/animals/${animal.id}`)}
export async function deleteAnimal(data:FormData){const id=z.uuid().safeParse(data.get("id"));if(!id.success)return;const supabase=await createClient();await supabase.from("animals").delete().eq("id",id.data);revalidatePath("/animals");redirect("/animals")}

async function context(data:FormData){const animalId=z.uuid().safeParse(data.get("animal_id"));if(!animalId.success)return null;const supabase=await createClient();const {data:auth}=await supabase.auth.getClaims();const ownerId=auth?.claims?.sub;return ownerId?{animalId:animalId.data,supabase,ownerId}:null}
export async function addMedicalRecord(_:FormState,data:FormData):Promise<FormState>{const ctx=await context(data);if(!ctx)return{error:"Your session expired."};const parsed=z.object({title:z.string().trim().min(1).max(160),record_type:z.string().trim().min(1).max(60),occurred_at:z.string().min(1),notes:z.string().max(5000).optional()}).safeParse(Object.fromEntries(data));if(!parsed.success)return{error:"Complete the required record fields."};const {error}=await ctx.supabase.from("medical_records").insert({...parsed.data,notes:parsed.data.notes||null,animal_id:ctx.animalId,owner_id:ctx.ownerId});if(error)return{error:error.message};revalidatePath(`/animals/${ctx.animalId}`);return{}}
export async function addVaccination(_:FormState,data:FormData):Promise<FormState>{const ctx=await context(data);if(!ctx)return{error:"Your session expired."};const parsed=z.object({vaccine_name:z.string().trim().min(1).max(160),administered_at:z.string().min(1),next_due_at:z.string().optional(),veterinarian_clinic:z.string().max(200).optional(),notes:z.string().max(3000).optional()}).safeParse(Object.fromEntries(data));if(!parsed.success)return{error:"Complete the required vaccination fields."};const v=parsed.data;const {error}=await ctx.supabase.from("vaccinations").insert({...v,next_due_at:v.next_due_at||null,veterinarian_clinic:v.veterinarian_clinic||null,notes:v.notes||null,animal_id:ctx.animalId,owner_id:ctx.ownerId});if(error)return{error:error.message};revalidatePath(`/animals/${ctx.animalId}`);return{}}
export async function addMedication(_:FormState,data:FormData):Promise<FormState>{const ctx=await context(data);if(!ctx)return{error:"Your session expired."};const parsed=z.object({name:z.string().trim().min(1).max(160),prescribed_instructions:z.string().trim().min(1).max(2000),start_date:z.string().optional(),end_date:z.string().optional(),purpose:z.string().max(500).optional()}).safeParse(Object.fromEntries(data));if(!parsed.success)return{error:"Enter a medicine name and instructions."};const v=parsed.data;const {error}=await ctx.supabase.from("medications").insert({...v,start_date:v.start_date||null,end_date:v.end_date||null,purpose:v.purpose||null,animal_id:ctx.animalId,owner_id:ctx.ownerId});if(error)return{error:error.message};revalidatePath(`/animals/${ctx.animalId}`);return{}}
